// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dairy_movies.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDairyMovie = `-- name: CreateDairyMovie :one
INSERT INTO dairy_movies(id, movie_id, user_id, watched_at, is_rewatched, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
RETURNING id, movie_id, user_id, watched_at, created_at, updated_at, is_rewatched
`

type CreateDairyMovieParams struct {
	MovieID     int32
	UserID      uuid.UUID
	WatchedAt   time.Time
	IsRewatched bool
}

func (q *Queries) CreateDairyMovie(ctx context.Context, arg CreateDairyMovieParams) (DairyMovie, error) {
	row := q.db.QueryRowContext(ctx, createDairyMovie,
		arg.MovieID,
		arg.UserID,
		arg.WatchedAt,
		arg.IsRewatched,
	)
	var i DairyMovie
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRewatched,
	)
	return i, err
}

const deleteDairyMovie = `-- name: DeleteDairyMovie :exec
DELETE FROM dairy_movies 
  WHERE user_id = $1 
  AND movie_id = $2
`

type DeleteDairyMovieParams struct {
	UserID  uuid.UUID
	MovieID int32
}

func (q *Queries) DeleteDairyMovie(ctx context.Context, arg DeleteDairyMovieParams) error {
	_, err := q.db.ExecContext(ctx, deleteDairyMovie, arg.UserID, arg.MovieID)
	return err
}

const getDairyMovie = `-- name: GetDairyMovie :one
SELECT FROM dairy_movies
  WHERE user_id = $1
  AND movie_id = $2
`

type GetDairyMovieParams struct {
	UserID  uuid.UUID
	MovieID int32
}

type GetDairyMovieRow struct {
}

func (q *Queries) GetDairyMovie(ctx context.Context, arg GetDairyMovieParams) (GetDairyMovieRow, error) {
	row := q.db.QueryRowContext(ctx, getDairyMovie, arg.UserID, arg.MovieID)
	var i GetDairyMovieRow
	err := row.Scan()
	return i, err
}

const updateDairyMovie = `-- name: UpdateDairyMovie :one
UPDATE dairy_movies
SET watched_at = $1,
  is_rewatched = $2,
  updated_at = NOW()
WHERE user_id = $3
RETURNING id, movie_id, user_id, watched_at, created_at, updated_at, is_rewatched
`

type UpdateDairyMovieParams struct {
	WatchedAt   time.Time
	IsRewatched bool
	UserID      uuid.UUID
}

func (q *Queries) UpdateDairyMovie(ctx context.Context, arg UpdateDairyMovieParams) (DairyMovie, error) {
	row := q.db.QueryRowContext(ctx, updateDairyMovie, arg.WatchedAt, arg.IsRewatched, arg.UserID)
	var i DairyMovie
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsRewatched,
	)
	return i, err
}
