// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type MovieDiary struct {
	ID        uuid.UUID
	MovieID   int32
	UserID    uuid.UUID
	WatchedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MovieReview struct {
	ID        uuid.UUID
	MovieID   int32
	UserID    uuid.UUID
	Review    string
	Rating    float32
	IsSpoiler bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Username       string
	HashedPassword string
	IsPremium      bool
	Name           string
}
