// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Movie struct {
	ID            uuid.UUID
	TmdbID        int32
	ImdbID        string
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	VoteAverage   float64
	VoteCount     int32
	Revenue       int64
	Homepage      string
	Genres        pqtype.NullRawMessage
	Runtime       int32
	Trailer       string
	Tagline       string
	CreatedAt     time.Time
}

type MovieDiary struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	UserID    uuid.UUID
	WatchedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MovieReview struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	UserID    uuid.UUID
	Review    string
	Rating    float32
	IsSpoiler bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	Username       string
	HashedPassword string
	IsPremium      bool
	Name           string
	Bio            string
}

type Watchlist struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}
