// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie_diaries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createMovieDiary = `-- name: CreateMovieDiary :one
INSERT INTO movie_diaries(id, movie_id, user_id, watched_at, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW(), NOW())
RETURNING id, movie_id, user_id, watched_at, created_at, updated_at
`

type CreateMovieDiaryParams struct {
	MovieID   uuid.UUID
	UserID    uuid.UUID
	WatchedAt time.Time
}

func (q *Queries) CreateMovieDiary(ctx context.Context, arg CreateMovieDiaryParams) (MovieDiary, error) {
	row := q.db.QueryRowContext(ctx, createMovieDiary, arg.MovieID, arg.UserID, arg.WatchedAt)
	var i MovieDiary
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMovieDiary = `-- name: DeleteMovieDiary :exec
DELETE FROM movie_diaries 
  WHERE user_id = $1 
  AND id = $2
`

type DeleteMovieDiaryParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteMovieDiary(ctx context.Context, arg DeleteMovieDiaryParams) error {
	_, err := q.db.ExecContext(ctx, deleteMovieDiary, arg.UserID, arg.ID)
	return err
}

const getDiary = `-- name: GetDiary :one
SELECT id, movie_id, user_id, watched_at, created_at, updated_at FROM movie_diaries WHERE id = $1
`

func (q *Queries) GetDiary(ctx context.Context, id uuid.UUID) (MovieDiary, error) {
	row := q.db.QueryRowContext(ctx, getDiary, id)
	var i MovieDiary
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieDiariesForUser = `-- name: GetMovieDiariesForUser :many
SELECT id, movie_id, user_id, watched_at, created_at, updated_at FROM movie_diaries
  WHERE user_id = $1
  AND movie_id = $2
`

type GetMovieDiariesForUserParams struct {
	UserID  uuid.UUID
	MovieID uuid.UUID
}

func (q *Queries) GetMovieDiariesForUser(ctx context.Context, arg GetMovieDiariesForUserParams) ([]MovieDiary, error) {
	rows, err := q.db.QueryContext(ctx, getMovieDiariesForUser, arg.UserID, arg.MovieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieDiary
	for rows.Next() {
		var i MovieDiary
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.WatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDiaries = `-- name: GetUserDiaries :many
SELECT
    movie_diaries.id, movie_diaries.movie_id, movie_diaries.user_id, movie_diaries.watched_at, movie_diaries.created_at, movie_diaries.updated_at,
    movies.tmdb_id,
    movies.imdb_id,
    movies.title,
    movies.original_title,
    movies.poster_path,
    movies.backdrop_path,
    movies.overview,
    movies.release_date,
    movies.vote_average,
    movies.vote_count,
    movies.revenue,
    movies.homepage,
    movies.genres,
    movies.runtime,
    movies.trailer,
    movies.tagline
FROM movie_diaries
JOIN movies
ON movie_diaries.movie_id = movies.id
WHERE movie_diaries.user_id = $1
`

type GetUserDiariesRow struct {
	ID            uuid.UUID
	MovieID       uuid.UUID
	UserID        uuid.UUID
	WatchedAt     time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TmdbID        int32
	ImdbID        string
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	VoteAverage   float64
	VoteCount     int32
	Revenue       int64
	Homepage      string
	Genres        pqtype.NullRawMessage
	Runtime       int32
	Trailer       string
	Tagline       string
}

func (q *Queries) GetUserDiaries(ctx context.Context, userID uuid.UUID) ([]GetUserDiariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserDiaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDiariesRow
	for rows.Next() {
		var i GetUserDiariesRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.WatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TmdbID,
			&i.ImdbID,
			&i.Title,
			&i.OriginalTitle,
			&i.PosterPath,
			&i.BackdropPath,
			&i.Overview,
			&i.ReleaseDate,
			&i.VoteAverage,
			&i.VoteCount,
			&i.Revenue,
			&i.Homepage,
			&i.Genres,
			&i.Runtime,
			&i.Trailer,
			&i.Tagline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovieDiary = `-- name: UpdateMovieDiary :one
UPDATE movie_diaries
SET watched_at = $1,
  updated_at = NOW()
WHERE id = $2
RETURNING id, movie_id, user_id, watched_at, created_at, updated_at
`

type UpdateMovieDiaryParams struct {
	WatchedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateMovieDiary(ctx context.Context, arg UpdateMovieDiaryParams) (MovieDiary, error) {
	row := q.db.QueryRowContext(ctx, updateMovieDiary, arg.WatchedAt, arg.ID)
	var i MovieDiary
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
