// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie_reviews.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMovieReview = `-- name: CreateMovieReview :one
INSERT INTO movie_reviews(id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at) 
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at
`

type CreateMovieReviewParams struct {
	MovieID   int32
	UserID    uuid.UUID
	Review    string
	Rating    float32
	IsSpoiler bool
}

func (q *Queries) CreateMovieReview(ctx context.Context, arg CreateMovieReviewParams) (MovieReview, error) {
	row := q.db.QueryRowContext(ctx, createMovieReview,
		arg.MovieID,
		arg.UserID,
		arg.Review,
		arg.Rating,
		arg.IsSpoiler,
	)
	var i MovieReview
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Review,
		&i.Rating,
		&i.IsSpoiler,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
