// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addMovie = `-- name: AddMovie :one
INSERT INTO movies (
    id,
    tmdb_id,
    imdb_id,
    title,
    original_title,
    poster_path,
    backdrop_path,
    overview,
    release_date,
    vote_average,
    vote_count,
    revenue,
    homepage,
    genres,
    runtime,
    tagline,
    trailer,
    created_at
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,          
    $10,
    $11,
    $12,
    $13::jsonb,  
    $14,
    $15,
    $16,
    NOW()
)
ON CONFLICT (tmdb_id) DO UPDATE
SET 
    title = EXCLUDED.title,
    original_title = EXCLUDED.original_title,
    poster_path = EXCLUDED.poster_path,
    backdrop_path = EXCLUDED.backdrop_path,
    overview = EXCLUDED.overview,
    release_date = EXCLUDED.release_date,
    vote_average = EXCLUDED.vote_average,
    genres = EXCLUDED.genres,
    runtime = EXCLUDED.runtime,
    tagline = EXCLUDED.tagline
RETURNING id, tmdb_id, imdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, vote_count, revenue, homepage, genres, runtime, trailer, tagline, created_at
`

type AddMovieParams struct {
	TmdbID        int32
	ImdbID        string
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	VoteAverage   float64
	VoteCount     int32
	Revenue       int64
	Homepage      string
	Column13      json.RawMessage
	Runtime       int32
	Tagline       string
	Trailer       string
}

func (q *Queries) AddMovie(ctx context.Context, arg AddMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, addMovie,
		arg.TmdbID,
		arg.ImdbID,
		arg.Title,
		arg.OriginalTitle,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Overview,
		arg.ReleaseDate,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Revenue,
		arg.Homepage,
		arg.Column13,
		arg.Runtime,
		arg.Tagline,
		arg.Trailer,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Revenue,
		&i.Homepage,
		&i.Genres,
		&i.Runtime,
		&i.Trailer,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllMovies = `-- name: DeleteAllMovies :exec
DELETE FROM movies
`

func (q *Queries) DeleteAllMovies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMovies)
	return err
}

const getMovieById = `-- name: GetMovieById :one
SELECT id, tmdb_id, imdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, vote_count, revenue, homepage, genres, runtime, trailer, tagline, created_at FROM movies WHERE id = $1
`

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieById, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Revenue,
		&i.Homepage,
		&i.Genres,
		&i.Runtime,
		&i.Trailer,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieByTmdbId = `-- name: GetMovieByTmdbId :one
SELECT id, tmdb_id, imdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, vote_count, revenue, homepage, genres, runtime, trailer, tagline, created_at FROM movies WHERE tmdb_id = $1
`

func (q *Queries) GetMovieByTmdbId(ctx context.Context, tmdbID int32) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByTmdbId, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Revenue,
		&i.Homepage,
		&i.Genres,
		&i.Runtime,
		&i.Trailer,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}

const getUserMetadataForMovie = `-- name: GetUserMetadataForMovie :one
SELECT 
    m.id AS movie_id,
    m.tmdb_id as tmdb_id,

    md.id AS diary_id,
    md.user_id AS diary_user_id,
    md.watched_at,
    md.created_at AS diary_created_at,
    md.updated_at AS diary_updated_at,

    (wl.movie_id IS NOT NULL) AS is_in_watchlist,

    r.id AS review_id,
    r.review,
    r.rating,
    r.is_spoiler,
    r.created_at AS review_created_at,
    r.updated_at AS review_updated_at

FROM movies m
LEFT JOIN movie_diaries md
    ON md.id = (
        SELECT id
        FROM movie_diaries
        WHERE movie_id = m.id AND md.user_id = $1
    )

LEFT JOIN watchlists wl
    ON m.id = wl.movie_id AND wl.user_id = $1

LEFT JOIN movie_reviews r
    ON r.id = (
        SELECT id
        FROM movie_reviews
        WHERE movie_id = m.id AND r.user_id = $1
    )

WHERE m.id = $2
`

type GetUserMetadataForMovieParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetUserMetadataForMovieRow struct {
	MovieID         uuid.UUID
	TmdbID          int32
	DiaryID         uuid.NullUUID
	DiaryUserID     uuid.NullUUID
	WatchedAt       sql.NullTime
	DiaryCreatedAt  sql.NullTime
	DiaryUpdatedAt  sql.NullTime
	IsInWatchlist   interface{}
	ReviewID        uuid.NullUUID
	Review          sql.NullString
	Rating          sql.NullFloat64
	IsSpoiler       sql.NullBool
	ReviewCreatedAt sql.NullTime
	ReviewUpdatedAt sql.NullTime
}

func (q *Queries) GetUserMetadataForMovie(ctx context.Context, arg GetUserMetadataForMovieParams) (GetUserMetadataForMovieRow, error) {
	row := q.db.QueryRowContext(ctx, getUserMetadataForMovie, arg.UserID, arg.ID)
	var i GetUserMetadataForMovieRow
	err := row.Scan(
		&i.MovieID,
		&i.TmdbID,
		&i.DiaryID,
		&i.DiaryUserID,
		&i.WatchedAt,
		&i.DiaryCreatedAt,
		&i.DiaryUpdatedAt,
		&i.IsInWatchlist,
		&i.ReviewID,
		&i.Review,
		&i.Rating,
		&i.IsSpoiler,
		&i.ReviewCreatedAt,
		&i.ReviewUpdatedAt,
	)
	return i, err
}
