// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie_reviews.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMovieReview = `-- name: CreateMovieReview :one
INSERT INTO movie_reviews(id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at) 
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at
`

type CreateMovieReviewParams struct {
	MovieID   uuid.UUID
	UserID    uuid.UUID
	Review    string
	Rating    float32
	IsSpoiler bool
}

func (q *Queries) CreateMovieReview(ctx context.Context, arg CreateMovieReviewParams) (MovieReview, error) {
	row := q.db.QueryRowContext(ctx, createMovieReview,
		arg.MovieID,
		arg.UserID,
		arg.Review,
		arg.Rating,
		arg.IsSpoiler,
	)
	var i MovieReview
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Review,
		&i.Rating,
		&i.IsSpoiler,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM movie_reviews WHERE movie_id = $1 AND user_id = $2
`

type DeleteReviewParams struct {
	MovieID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) error {
	_, err := q.db.ExecContext(ctx, deleteReview, arg.MovieID, arg.UserID)
	return err
}

const getMovieReviews = `-- name: GetMovieReviews :many
SELECT 
    r.id,
    r.movie_id,
    r.review,
    r.rating,
    r.is_spoiler,
    r.created_at,
    r.updated_at,
    u.id AS user_id,
    u.name AS user_name,
    u.email AS user_email,
    u.username AS user_username,
    u.is_premium AS user_is_premium
FROM movie_reviews r
INNER JOIN users u ON r.user_id = u.id
WHERE r.movie_id = $1
`

type GetMovieReviewsRow struct {
	ID            uuid.UUID
	MovieID       uuid.UUID
	Review        string
	Rating        float32
	IsSpoiler     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
	UserName      string
	UserEmail     string
	UserUsername  string
	UserIsPremium bool
}

func (q *Queries) GetMovieReviews(ctx context.Context, movieID uuid.UUID) ([]GetMovieReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovieReviews, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieReviewsRow
	for rows.Next() {
		var i GetMovieReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Review,
			&i.Rating,
			&i.IsSpoiler,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserUsername,
			&i.UserIsPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleMovieReview = `-- name: GetSingleMovieReview :one
SELECT id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at FROM movie_reviews WHERE id = $1
`

func (q *Queries) GetSingleMovieReview(ctx context.Context, id uuid.UUID) (MovieReview, error) {
	row := q.db.QueryRowContext(ctx, getSingleMovieReview, id)
	var i MovieReview
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Review,
		&i.Rating,
		&i.IsSpoiler,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReviews = `-- name: GetUserReviews :many
SELECT id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at FROM movie_reviews WHERE user_id = $1
`

func (q *Queries) GetUserReviews(ctx context.Context, userID uuid.UUID) ([]MovieReview, error) {
	rows, err := q.db.QueryContext(ctx, getUserReviews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieReview
	for rows.Next() {
		var i MovieReview
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.Review,
			&i.Rating,
			&i.IsSpoiler,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovieReview = `-- name: UpdateMovieReview :one
UPDATE movie_reviews
SET review = $1,
  is_spoiler = $2,
  rating = $3,
  updated_at = NOW()
WHERE movie_id = $4 AND user_id = $5
RETURNING id, movie_id, user_id, review, rating, is_spoiler, created_at, updated_at
`

type UpdateMovieReviewParams struct {
	Review    string
	IsSpoiler bool
	Rating    float32
	MovieID   uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateMovieReview(ctx context.Context, arg UpdateMovieReviewParams) (MovieReview, error) {
	row := q.db.QueryRowContext(ctx, updateMovieReview,
		arg.Review,
		arg.IsSpoiler,
		arg.Rating,
		arg.MovieID,
		arg.UserID,
	)
	var i MovieReview
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Review,
		&i.Rating,
		&i.IsSpoiler,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
