// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addMovie = `-- name: AddMovie :one
INSERT INTO movies (
    id,
    tmdb_id,
    title,
    original_title,
    poster_path,
    backdrop_path,
    overview,
    release_date,
    vote_average,
    genres,
    runtime,
    status,
    tagline,
    created_at
) VALUES (
    gen_random_uuid(),              
    $1,                              
    $2,                              
    $3,                              
    $4,                              
    $5,                              
    $6,                              
    $7,                              
    $8,                              
    $9::jsonb,                       
    $10,                             
    $11,                             
    $12,                             
    NOW()                            
)
ON CONFLICT (tmdb_id) DO UPDATE
SET 
    title = EXCLUDED.title,
    original_title = EXCLUDED.original_title,
    poster_path = EXCLUDED.poster_path,
    backdrop_path = EXCLUDED.backdrop_path,
    overview = EXCLUDED.overview,
    release_date = EXCLUDED.release_date,
    vote_average = EXCLUDED.vote_average,
    genres = EXCLUDED.genres,
    runtime = EXCLUDED.runtime,
    status = EXCLUDED.status,
    tagline = EXCLUDED.tagline
RETURNING id, tmdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, genres, runtime, status, tagline, created_at
`

type AddMovieParams struct {
	TmdbID        int32
	Title         string
	OriginalTitle string
	PosterPath    string
	BackdropPath  string
	Overview      string
	ReleaseDate   time.Time
	VoteAverage   float64
	Column9       json.RawMessage
	Runtime       int32
	Status        string
	Tagline       string
}

func (q *Queries) AddMovie(ctx context.Context, arg AddMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, addMovie,
		arg.TmdbID,
		arg.Title,
		arg.OriginalTitle,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Overview,
		arg.ReleaseDate,
		arg.VoteAverage,
		arg.Column9,
		arg.Runtime,
		arg.Status,
		arg.Tagline,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.Genres,
		&i.Runtime,
		&i.Status,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieById = `-- name: GetMovieById :one
SELECT id, tmdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, genres, runtime, status, tagline, created_at FROM movies WHERE id = $1
`

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieById, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.Genres,
		&i.Runtime,
		&i.Status,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieByTmdbId = `-- name: GetMovieByTmdbId :one

SELECT id, tmdb_id, title, original_title, poster_path, backdrop_path, overview, release_date, vote_average, genres, runtime, status, tagline, created_at FROM movies WHERE tmdb_id = $1
`

// -- name: AddMovie :one
// INSERT INTO movies (
//
//	id,
//	tmdb_id,
//	title,
//	original_title,
//	poster_path,
//	backdrop_path,
//	overview,
//	release_date,
//	vote_average,
//	genres,
//	runtime,
//	status,
//	tagline,
//	created_at
//
// ) VALUES (
//
//	gen_random_uuid(),
//	$1,
//	$2,
//	$3,
//	$4,
//	$5,
//	$6,
//	$7,
//	$8,
//	$9::jsonb,
//	$10,
//	$11,
//	$12,
//	NOW()
//
// )
// RETURNING *;
func (q *Queries) GetMovieByTmdbId(ctx context.Context, tmdbID int32) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByTmdbId, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Overview,
		&i.ReleaseDate,
		&i.VoteAverage,
		&i.Genres,
		&i.Runtime,
		&i.Status,
		&i.Tagline,
		&i.CreatedAt,
	)
	return i, err
}
