// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlists.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addToWatchlist = `-- name: AddToWatchlist :one
INSERT INTO watchlists (id, user_id, movie_id, created_at)
VALUES (gen_random_uuid(), $1, $2, NOW())
RETURNING id, movie_id, user_id, created_at
`

type AddToWatchlistParams struct {
	UserID  uuid.UUID
	MovieID int32
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, addToWatchlist, arg.UserID, arg.MovieID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
