// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlists.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addToWatchlist = `-- name: AddToWatchlist :one
INSERT INTO watchlists (id, user_id, movie_id, created_at)
VALUES (gen_random_uuid(), $1, $2, NOW())
RETURNING id, movie_id, user_id, created_at
`

type AddToWatchlistParams struct {
	UserID  uuid.UUID
	MovieID uuid.UUID
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, addToWatchlist, arg.UserID, arg.MovieID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWatchlist = `-- name: GetUserWatchlist :many
SELECT id, movie_id, user_id, created_at FROM watchlists WHERE user_id = $1
`

func (q *Queries) GetUserWatchlist(ctx context.Context, userID uuid.UUID) ([]Watchlist, error) {
	rows, err := q.db.QueryContext(ctx, getUserWatchlist, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watchlist
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchlistRecord = `-- name: GetWatchlistRecord :one
SELECT id, movie_id, user_id, created_at FROM watchlists WHERE movie_id = $1 AND user_id = $2
`

type GetWatchlistRecordParams struct {
	MovieID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetWatchlistRecord(ctx context.Context, arg GetWatchlistRecordParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistRecord, arg.MovieID, arg.UserID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const removeMovieFromWatchlist = `-- name: RemoveMovieFromWatchlist :exec
DELETE FROM watchlists WHERE movie_id = $1 AND user_id = $2
`

type RemoveMovieFromWatchlistParams struct {
	MovieID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveMovieFromWatchlist(ctx context.Context, arg RemoveMovieFromWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, removeMovieFromWatchlist, arg.MovieID, arg.UserID)
	return err
}
